# ======================
# DATABASE (LOCAL)
# ======================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/ORCLPDB
spring.datasource.username=career_user
spring.datasource.password=career123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ======================
# HIBERNATE (DEV)
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ======================
# LOGGING (DEV)
# ======================
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG
logging.level.org.springframework.security=DEBUG

# ======================
# JWT CONFIG
# ======================
jwt.secret=${JWT_SECRET}
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000

# ======================
# RATE LIMITING
# ======================
security.rate-limit.login.max-requests=5
security.rate-limit.login.window-seconds=60

security.rate-limit.refresh.max-requests=10
security.rate-limit.refresh.window-seconds=60